name=SimpleButton
version=1.0.0
author=Evgeny Gekht (fork https://github.com/e-tinkers/button)
maintainer=Evgeny Gwkht<egeht13@gmail,com>
sentence=Простая библиотека для кнопки с подавлением дребезга на битовых операциях.
paragraph=Обеспечивает быстрый антидребезг, отслеживание кликов, отпускания и удержания. Практически не расходует память.
category=Device Control
url=https://github.com/egeht
architectures=*
